name: HikaSurvival
main: me.santipingui58.survival.HikaSurvival
version: 1.4
api-version: 1.19
depends: [DiscordSRV,Essentials]
commands:
  structure:
    permission: hika.admin
  msg:
    description: msg
    aliases: [tell,message,whisper,w]
  reply:
    aliases: [r]
  hover: 
    description: hover
  warp: 
    description: warp
    aliases: [warps]
  home: 
    aliases: [homes]
  delhome: 
    description: delhome
  sethome: 
    description: sethome
  bank: 
    description: bank
  banktop: 
    description: banktop
  stream: 
    description: banktop
    aliases: [directo,twitch]
  bypass: 
    description: banktop